# Generated by Django 3.2 on 2021-06-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=20)),
                ('temperature', models.CharField(max_length=20)),
                ('humidity', models.CharField(max_length=20)),
            ],
        ),
    ]
