# Generated by Django 3.2 on 2021-06-16 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(max_length=20)),
                ('city_name', models.CharField(max_length=20)),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='weatherinfo',
            name='city_name',
        ),
        migrations.RemoveField(
            model_name='weatherinfo',
            name='country_name',
        ),
    ]
