# Generated by Django 3.2 on 2021-06-21 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20210616_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityinfo',
            name='city_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.weatherinfo'),
        ),
    ]
